GET http://localhost:5000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiR25hbmkifSwiaWF0IjoxNzI0NTU1NDI0fQ.nJNhxsE6HFixldTtV6szypVuUDOPfEJo02fJzU8tAgM


###
POST  http://localhost:5000/api/blogs/create
Content-Type: application/json

{
    "title": "My First Blog",
    "content": "To Start Blogging, one mneed to have these things",
    "userName": "Gnani"
}

###
PUT  http://localhost:5000/api/blogs/66c9eaafa34ff3d5683ebd47
Content-Type: application/json

{
    "title": "My Seond Blog",
    "content": "To Start Blogging, one mneed to have these things",
    "userName": "Gnani",
    "upVotesCount": "30"
}

###
DELETE http://localhost:5000/api/blogs/66c9eabdd2fe248ad7f3a33d

###
POST http://localhost:5000/api/auth/register 
Content-Type: application/json

{
    "username": "user1",
    "password": "12345"
}

###
POST http://localhost:5000/api/auth/login 
Content-Type: application/json

{
    "username": "Gnani",
    "password": "12345"
}
